name: Playwright Tests
on:
  push:
    branches: [ main,master ]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Kill any process using port 5000
        run: kill -9 $(lsof -t -i:5000) 2>/dev/null || true
      - name: Start Server
        run: npm run start-prod & echo $! > server.pid
      - name: Run Playwright Tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30


